### ISSUE TITLE
camera模型参数加载

### ISSUE THREAD

**Issue by diyifirstone** [xmy0916/CASTOR#1]
请问您代码中camera_model加载的预训练模型参数是在哪里？
cluster_contrast_train_usl.py文件中的 torch.load(os.path.join(args.camera_model_dir,"model_best.pth.tar"))["state_dict"]；

这里加载的模型参数是自己预训练还是什么？

**Comment by xmy0916** [comment]
https://github.com/xmy0916/CASTOR#pre-trained-models
readme写了，你看看吧 @diyifirstone

**Comment by xmy0916** [comment]
参数就是用图像的相机ID训的相机分类模型 去掉了后面的分类层，拿来提图像的相机embedding

**Comment by diyifirstone** [comment]
请问您论文中，分别利用两个模型提取出特征，然后分别计算相似度矩阵，为什么还要相减呢？请问相减的逻辑是什么？谢谢。

**Comment by xmy0916** [comment]
两张reid图像的相似度可以理解为 行人相似度+相机相似度+其他相似度，两个相似度矩阵做差消除了部分相机相似度的影响。
